name: Build and Lint Check web application
on: push
jobs: 
  build-project:
    name: Build project
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Specifying a compatible Node.js version
    - name: Install NPM dependencies
      run: npm install
    - name: Build project assets
      run: npm run build
  lintTest:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Specifying a compatible Node.js version
      - name: Install dependencies
        run: npm install
      - name: Run Linting
        run: |
          echo "Running Linting Tests..."
          npm run lint
        env:
          CI: true